version: '3.0'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /opt/rabbitmq/data:/var/lib/rabbitmq
    container_name: rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/